# This makefile has been generated by clice - the command line coding ecosystem
#	more details at www.benningtons.net
# built on 19032020 at 2321

# Shell command variables
SHELL = /bin/sh
NASM = /usr/bin/nasm
NASM_FLAGS= -f bin -w+all

# This project's executable programs
all:	\
	fernOS.bin 

# Tidy-up.
clean:
	-rm *~
	rm fernOS.img

# Prepare image for operational use
install:
#mkdosfs is found in the debian dosfstools package
	@/sbin/mkdosfs -C fernOS.img 1440				#Create a new disk image
	@dd if=fernOS.bin of=fernOS.img conv=notrunc	#Transfer fernOS to disk image
	@echo "\nNew fernOS.img file created. Use makeUSB.sh to write it to a USB memory stick of floppy disk."

# Assembly routines and their dependencies

fernOS.bin: fernOS.asm fernOS_BIOS_library.asm fernOS_UTIL_library.asm fe_ascii.hsm
	$(NASM) $(NASM_FLAGS) $< -o $@
